---
- name: Create Azure resource group
  hosts: localhost
  gather_facts: false

  vars:
    location: "eastus"
    lb_pip_name: "lb-pip"

  tasks:

    - name: Fetch the Load Balancer Public IP
      azure.azcollection.azure_rm_publicipaddress_info:
        resource_group: "{{ res_group }}"
        name: "{{ lb_pip_name }}"
      register: lb_pip_info

    - name: Set IP as a fact
      ansible.builtin.set_fact:
        lb_ip: "{{ lb_pip_info.publicipaddresses[0].ip_address }}"

    - name: Wait for Load Balancer to report Healthy (HTTP 200)
      ansible.builtin.uri:
        url: "http://{{ lb_ip }}"
        return_content: yes
      register: lb_res
      # This will retry for up to 2 minutes (12 * 10s)
      until: lb_res.status == 200 and "Hello from Azure VM" in lb_res.content
      retries: 12
      delay: 10

    - name: 🚀 Success! Application is Live
      ansible.builtin.debug:
        msg:
          - "--------------------------------------------------------"
          - " VERIFICATION COMPLETE"
          - " URL: http://{{ lb_ip }}"
          - " SERVER RESPONDED WITH: {{ lb_res.content | striptags | trim }}"
          - "--------------------------------------------------------"