---
- name: Delete Azure resource group
  hosts: localhost
  gather_facts: false

  vars:
    location: "eastus"

  tasks:

    - name: Delete Resource Group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ res_group }}"
        state: absent
        force_delete_nonempty: true
