---
- name: Provision Azure networking
  hosts: localhost
  gather_facts: false
  vars:
    res_group: "RGDefaultDemo"
    location: "eastus"
    vm_name: "rhel-web"

  tasks:

    - name: Create Virtual Network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ res_group }}"
        name: "demo-vnet"
        address_prefixes: "10.0.0.0/16"

    - name: Create Subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ res_group }}"
        name: "demo-subnet"
        address_prefix: "10.0.1.0/24"
        virtual_network_name: "demo-vnet"

    - name: Create Network Security Group
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ res_group }}"
        name: "demo-nsg"
        rules:
          - name: 'AllowSSH'
            protocol: Tcp
            destination_port_range: 22
            source_address_prefix: '*'
            access: Allow
            priority: 101
            direction: Inbound
          - name: 'AllowHTTP'
            protocol: Tcp
            destination_port_range: 80
            source_address_prefix: '*'
            access: Allow
            priority: 102
            direction: Inbound

    - name: Create Public IP for Load Balancer
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ res_group }}"
        allocation_method: Static
        name: "lb-pip"
        sku: Standard

    - name: Create Individual Public IPs for VM Management
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ res_group }}"
        name: "vm-pip-{{ item }}"
        allocation_method: Static
        sku: Standard
      loop: [1, 2]

    - name: Create Load Balancer (HA)
      azure.azcollection.azure_rm_loadbalancer:
        resource_group: "{{ res_group }}"
        name: "web-lb"
        sku: Standard
        frontend_ip_configurations:
          - name: "frontend-config"
            public_ip_address: "lb-pip"
        backend_address_pools:
          - name: "web-backend-pool"
        probes:
          - name: "http-probe"
            port: 80
            protocol: Http
            request_path: "/"
        load_balancing_rules:
          - name: "http-rule"
            frontend_ip_configuration: "frontend-config"
            backend_address_pool: "web-backend-pool"
            probe: "http-probe"
            protocol: Tcp
            frontend_port: 80
            backend_port: 80
            load_distribution: Default
            idle_timeout: 4
