---
- name: Set a stat
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Set a stat to carry through the workflow
      ansible.builtin.set_stats:
        data:
          var2: stat
