---
- name: Show secrets from vaulted file
  hosts: all
  gather_facts: false
  
  vars_files:
    - not_so_secret.yml

  tasks:
    - name: Attempt to show vault password
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.env', 'MY_ANSIBLE_VAULT_PASSWORD') }}"

    - name: Super secret text
      ansible.builtin.debug:
        var: super_secret_text
