---
- name: Have a little nap time
  hosts: all
  gather_facts: true
  become: false

  tasks:

    - name: Output the number of forks
      ansible.builtin.debug:
        var: ansible_forks
        
    - name: Sleep a number of seconds
      ansible.builtin.pause:
        seconds: "{{ timer | default(10) | int }}"

    - name: All done
      ansible.builtin.debug:
        msg: "Finally done waiting!"
