---
- name: Have a little nap time
  hosts: all
  gather_facts: false
  become: false

  tasks:

    - name: Sleep a number of seconds
      ansible.builtin.pause:
        seconds: "{{ timer | default(10) }}"

