---
- name: Test overriding variables in Workflows
  hosts: all
  gather_facts: false
  become: false
  strategy: free

  vars:
    var1: local
    var2: local

  tasks:
    - name: Print variables
      ansible.builtin.debug:
        var: item
      loop:
        - "{{ var1 }}"
        - "{{ var2 }}"

    - name: Print variables
      ansible.builtin.debug:
        var: item
      loop:
        - "{{ var1 }}"
        - "{{ var2 }}"

    - name: Print variables
      ansible.builtin.debug:
        var: item
      loop:
        - "{{ var1 }}"
        - "{{ var2 }}"
