---
- name: Test overriding variables in Workflows
  hosts: all
  gather_facts: false
  become: false

  vars:
    var1: "This is var1"
    var2: "This is var2"

  tasks:
    - name: Print variables
      ansible.builtin.debug:
        var: item
      loop:
        - var1
        - var2
        - var3

